import { Enterprise, FleetVehicle, TripManifest, User } from "../types";

export const INITIAL_ENTERPRISE: Enterprise = {
  id: "ent-blr-01",
  name: "Infosys & TechNexus Mobility Consortium",
  cinNumber: "U72200KA2023PTC178941",
  contractPermitRef: "KA-RTO-CC-2024-918-BLR",
  headquarters: "EcoSpace Outer Ring Road, Bellandur, Bengaluru 560103",
  contactEmail: "transit-ops@technexus.in",
  targetOccupancyPct: 90,
  esgMonthlyTargetKgCo2: 12500,
};

export const MOCK_USERS: User[] = [
  {
    id: "usr-commuter-01",
    name: "Aakash Sharma",
    email: "aakash.s@technexus.in",
    phone: "+91 98451 22345",
    role: "COMMUTER",
    enterpriseId: "ent-blr-01",
    homeAddress: "Sobha Dream Acres, Panathur Road",
    homeLat: 12.9348,
    homeLng: 77.7025,
    shiftTime: "08:30 AM - 05:30 PM",
  },
  {
    id: "usr-commuter-02",
    name: "Priya Sundaram",
    email: "priya.s@technexus.in",
    phone: "+91 97412 88412",
    role: "COMMUTER",
    enterpriseId: "ent-blr-01",
    homeAddress: "Prestige Silver Oak, Whitefield",
    homeLat: 12.9372,
    homeLng: 77.7051,
    shiftTime: "08:30 AM - 05:30 PM",
  },
  {
    id: "usr-commuter-03",
    name: "Rohan Verma",
    email: "rohan.v@technexus.in",
    phone: "+91 96118 43901",
    role: "COMMUTER",
    enterpriseId: "ent-blr-01",
    homeAddress: "Assetz Marq, Kannamangala",
    homeLat: 12.9331,
    homeLng: 77.6989,
    shiftTime: "08:30 AM - 05:30 PM",
  },
  {
    id: "usr-driver-01",
    name: "Raghavendra Gowda",
    email: "r.gowda@yatramesh.in",
    phone: "+91 94480 55192",
    role: "DRIVER",
    enterpriseId: "ent-blr-01",
  },
  {
    id: "usr-hr-01",
    name: "Meera Krishnan",
    email: "hr-mobility@technexus.in",
    phone: "+91 98801 11234",
    role: "HR_ADMIN",
    enterpriseId: "ent-blr-01",
  },
  {
    id: "usr-dispatcher-01",
    name: "Suresh Patil (Ops Desk)",
    email: "suresh.ops@yatramesh.in",
    phone: "+91 99000 77112",
    role: "DISPATCHER",
    enterpriseId: "ent-blr-01",
  },
];

export const MOCK_VEHICLES: FleetVehicle[] = [
  {
    id: "veh-01",
    registrationNumber: "KA 03 MJ 4021",
    vehicleType: "TEMPO_TRAVELER",
    seatCapacity: 12,
    makeModel: "Force Traveler Electric 3350",
    rtoPermitExpiry: "2027-11-30",
    isYellowBoardCompliant: true,
    driverId: "usr-driver-01",
    currentLat: 12.9312,
    currentLng: 77.6895,
    speedKmph: 28,
    fuelType: "EV",
  },
  {
    id: "veh-02",
    registrationNumber: "KA 05 AA 7890",
    vehicleType: "MINIBUS",
    seatCapacity: 24,
    makeModel: "Tata Winger Smart CNG",
    rtoPermitExpiry: "2026-10-15",
    isYellowBoardCompliant: true,
    driverId: "usr-driver-02",
    currentLat: 12.9421,
    currentLng: 77.712,
    speedKmph: 34,
    fuelType: "CNG",
  },
  {
    id: "veh-03",
    registrationNumber: "KA 01 AG 1122",
    vehicleType: "SHARED_AUTO",
    seatCapacity: 3,
    makeModel: "Bajaj RE E-Tec 9.0",
    rtoPermitExpiry: "2028-02-14",
    isYellowBoardCompliant: true,
    driverId: "usr-driver-03",
    currentLat: 12.939,
    currentLng: 77.695,
    speedKmph: 22,
    fuelType: "EV",
  },
];

// Sample realistic Bengaluru Outer Ring Road Corridor Polyline coordinates
export const SAMPLE_CORRIDOR_POLYLINE: [number, number][] = [
  [12.9428, 77.7152], // Start: Marathahalli ORR Junction
  [12.9395, 77.7081], // Kadubeesanahalli Overpass
  [12.9362, 77.7015], // Cisco - Wells Fargo Gateway
  [12.9324, 77.6948], // Bellandur Central Hub
  [12.9288, 77.6881], // EcoSpace Pedestrian Skywalk
  [12.9255, 77.6823], // RMZ Ecoworld Main Tech Gate (Destination)
];

export const INITIAL_MANIFEST: TripManifest = {
  id: "mnf-blr-8821",
  manifestNumber: "MNF-BLR-2026-08821",
  enterpriseId: "ent-blr-01",
  vehicleId: "veh-01",
  driverId: "usr-driver-01",
  driverName: "Raghavendra Gowda",
  driverPhone: "+91 94480 55192",
  vehicleRegistration: "KA 03 MJ 4021",
  vehicleType: "TEMPO_TRAVELER",
  seatCapacity: 12,
  shiftWindow: "08:30 AM - 09:15 AM",
  status: "EN_ROUTE",
  occupancyRatePct: 91.7, // 11 seats out of 12 filled (>=90%)
  totalWalkDistanceMeters: 890,
  avgWalkDistanceMeters: 81, // Strict < 150m constraint met!
  carbonSavedKg: 42.6,
  routePolyline: SAMPLE_CORRIDOR_POLYLINE,
  virtualStops: [
    {
      id: "vstop-01",
      name: "Kadubeesanahalli Bus Bay (West Geofence)",
      lat: 12.9395,
      lng: 77.7081,
      radiusMeters: 150,
      assignedPassengerIds: ["usr-commuter-02", "pax-04", "pax-05", "pax-06"],
      estimatedArrivalMin: 6,
    },
    {
      id: "vstop-02",
      name: "Cisco Green Glen Corner (Virtual Node)",
      lat: 12.9362,
      lng: 77.7015,
      radiusMeters: 150,
      assignedPassengerIds: ["usr-commuter-01", "pax-07", "pax-08"],
      estimatedArrivalMin: 12,
    },
    {
      id: "vstop-03",
      name: "Bellandur Outer Ring Road Walkover",
      lat: 12.9324,
      lng: 77.6948,
      radiusMeters: 150,
      assignedPassengerIds: ["usr-commuter-03", "pax-09", "pax-10", "pax-11"],
      estimatedArrivalMin: 19,
    },
    {
      id: "vstop-04",
      name: "RMZ Ecoworld Drop Campus Gate 2",
      lat: 12.9255,
      lng: 77.6823,
      radiusMeters: 150,
      assignedPassengerIds: [],
      estimatedArrivalMin: 28,
    },
  ],
  passengers: [
    {
      id: "pax-01",
      tripId: "mnf-blr-8821",
      userId: "usr-commuter-01",
      name: "Aakash Sharma",
      seatNumber: "Seat 3B (Window)",
      pickupStopId: "vstop-02",
      pickupStopName: "Cisco Green Glen Corner",
      pickupLat: 12.9362,
      pickupLng: 77.7015,
      walkDistanceMeters: 78,
      boardingStatus: "PENDING",
      boardingToken: "YTR-9884-AAKASH-SEC-TOKEN",
    },
    {
      id: "pax-02",
      tripId: "mnf-blr-8821",
      userId: "usr-commuter-02",
      name: "Priya Sundaram",
      seatNumber: "Seat 1A (Aisle)",
      pickupStopId: "vstop-01",
      pickupStopName: "Kadubeesanahalli Bus Bay",
      pickupLat: 12.9395,
      pickupLng: 77.7081,
      walkDistanceMeters: 62,
      boardingStatus: "ONBOARDED",
      boardingToken: "YTR-1192-PRIYA-SEC-TOKEN",
      boardedAt: "08:34 AM",
    },
    {
      id: "pax-03",
      tripId: "mnf-blr-8821",
      userId: "usr-commuter-03",
      name: "Rohan Verma",
      seatNumber: "Seat 4C",
      pickupStopId: "vstop-03",
      pickupStopName: "Bellandur ORR Walkover",
      pickupLat: 12.9324,
      pickupLng: 77.6948,
      walkDistanceMeters: 110,
      boardingStatus: "PENDING",
      boardingToken: "YTR-6631-ROHAN-SEC-TOKEN",
    },
    {
      id: "pax-04",
      tripId: "mnf-blr-8821",
      userId: "usr-pax-04",
      name: "Ananya Iyer",
      seatNumber: "Seat 1B",
      pickupStopId: "vstop-01",
      pickupStopName: "Kadubeesanahalli Bus Bay",
      pickupLat: 12.9395,
      pickupLng: 77.7081,
      walkDistanceMeters: 85,
      boardingStatus: "ONBOARDED",
      boardingToken: "YTR-4481-ANANYA-SEC-TOKEN",
      boardedAt: "08:35 AM",
    },
    {
      id: "pax-05",
      tripId: "mnf-blr-8821",
      userId: "usr-pax-05",
      name: "Devendra Patil",
      seatNumber: "Seat 2A",
      pickupStopId: "vstop-01",
      pickupStopName: "Kadubeesanahalli Bus Bay",
      pickupLat: 12.9395,
      pickupLng: 77.7081,
      walkDistanceMeters: 92,
      boardingStatus: "ONBOARDED",
      boardingToken: "YTR-9902-DEV-SEC-TOKEN",
      boardedAt: "08:36 AM",
    },
    {
      id: "pax-06",
      tripId: "mnf-blr-8821",
      userId: "usr-pax-06",
      name: "Kavita Reddy",
      seatNumber: "Seat 2B",
      pickupStopId: "vstop-01",
      pickupStopName: "Kadubeesanahalli Bus Bay",
      pickupLat: 12.9395,
      pickupLng: 77.7081,
      walkDistanceMeters: 70,
      boardingStatus: "ONBOARDED",
      boardingToken: "YTR-2201-KAVITA-SEC-TOKEN",
      boardedAt: "08:36 AM",
    },
    {
      id: "pax-07",
      tripId: "mnf-blr-8821",
      userId: "usr-pax-07",
      name: "Vikram Malhotra",
      seatNumber: "Seat 3A",
      pickupStopId: "vstop-02",
      pickupStopName: "Cisco Green Glen Corner",
      pickupLat: 12.9362,
      pickupLng: 77.7015,
      walkDistanceMeters: 95,
      boardingStatus: "PENDING",
      boardingToken: "YTR-7721-VIKRAM-SEC-TOKEN",
    },
    {
      id: "pax-08",
      tripId: "mnf-blr-8821",
      userId: "usr-pax-08",
      name: "Sneha Nair",
      seatNumber: "Seat 3C",
      pickupStopId: "vstop-02",
      pickupStopName: "Cisco Green Glen Corner",
      pickupLat: 12.9362,
      pickupLng: 77.7015,
      walkDistanceMeters: 80,
      boardingStatus: "PENDING",
      boardingToken: "YTR-8812-SNEHA-SEC-TOKEN",
    },
    {
      id: "pax-09",
      tripId: "mnf-blr-8821",
      userId: "usr-pax-09",
      name: "Tanmay Deshmukh",
      seatNumber: "Seat 4A",
      pickupStopId: "vstop-03",
      pickupStopName: "Bellandur ORR Walkover",
      pickupLat: 12.9324,
      pickupLng: 77.6948,
      walkDistanceMeters: 104,
      boardingStatus: "PENDING",
      boardingToken: "YTR-5541-TANMAY-SEC-TOKEN",
    },
    {
      id: "pax-10",
      tripId: "mnf-blr-8821",
      userId: "usr-pax-10",
      name: "Zainab Fatima",
      seatNumber: "Seat 4B",
      pickupStopId: "vstop-03",
      pickupStopName: "Bellandur ORR Walkover",
      pickupLat: 12.9324,
      pickupLng: 77.6948,
      walkDistanceMeters: 65,
      boardingStatus: "PENDING",
      boardingToken: "YTR-3390-ZAINAB-SEC-TOKEN",
    },
    {
      id: "pax-11",
      tripId: "mnf-blr-8821",
      userId: "usr-pax-11",
      name: "Gaurav Joshi",
      seatNumber: "Seat 2C",
      pickupStopId: "vstop-03",
      pickupStopName: "Bellandur ORR Walkover",
      pickupLat: 12.9324,
      pickupLng: 77.6948,
      walkDistanceMeters: 71,
      boardingStatus: "PENDING",
      boardingToken: "YTR-1029-GAURAV-SEC-TOKEN",
    },
  ],
};
